### PR TITLE
rtl8812au: Fix build with kernel 4.11.9

### PR DESCRIPTION
**Pull request by MilhouseVH**
This patch is needed to compile with kernel 4.11.9 after https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/include/linux/netdevice.h?id=cf124db566e6b036b8bcbe8decbed740bdfac8c6

This kernel change was originally introduced in 4.12-rc6 but has been backported to 4.11.9

Build tested only, as I don't have any rtl8821au hardware.

### CODE REVIEW

**Comment by Orochimarufan** [comment]
This is based on the wrong branch; 4.3.20 is the current main branch

**Comment by MilhouseVH** [comment]
Master is the branch I'm using.

**Comment by MilhouseVH** [comment]
Sorry, you're right, I'll rebase on 4.3.20.

**Comment by MilhouseVH** [comment]
Arse, well that didn't go as planned. I'll push again.

**Pull request closed without merging**
