### PR TITLE
Update usb_intf.c

### PR DESCRIPTION
**Pull request by AndyPi**
support edimax 7811utc

### CODE REVIEW

**Comment by Grawp** [comment]
I won't merge this. Remove the makefile changes and make it be just one commit updating usb_intf.c
If you are new to git, read first three chapters from https://git-scm.com/book/en/v2

**Comment by AndyPi** [comment]
Im sorry, I dont really know how the other changes got there.  I only made one PR as far as I know although I did change the Makefile for my own purposes only.  I didnt imagine they would get included in the PR.  I will have to read the book !

**Comment by AndyPi** [comment]
Im going about this the wrong way.  I am editing on line in Git instead of creating a local version with git clone.  I thought it would be easier !  it seems not to be.  I cant see a way of reversing the changes apart from re-editing and generating more commits and more confusion. Unless you can offer simple advice best to delete my efforts and I will do a more thoughtful job soon. 
Thanks for your direction and my apologies for not being familiar enough with git to get it right 
regards
Andy

**Comment by Grawp** [comment]
I'll explain to you how to do it tomorrow or later today

**Comment by AndyPi** [comment]
Thanks

**Comment by Grawp** [comment]
Remember branches are just pointers.
```
git reset --hard ee9579663096ff12657a597fff42c83d4859e640 # Move your branch back to original state
# Note that moving branch pointer won't delete anything until you run garbage collecting. We will use this.
git cherry-pick cb1c2380c40ca43c1c3862e05deccffbc9a7c2de # Create one new commit by applying diff from the old one .. so you don't have to recreate it manually.
git push -f # Push it to github
```

**Comment by AndyPi** [comment]
As I said I dont have my own local branch.  I forked your repo and edited in a browser.  Anyway for me or you to just get rid of the PRs or to reset my fork without creating local branch.  Maybe Ill just have to create a local branch

**Comment by uminokoe** [comment]
I have submitted a pull request which only updates `usb_intf.c`. Please close this pull request.

**Pull request closed without merging**
