### PR TITLE
Kernel 4.8.0-4.8.1 compilation fix

### PR DESCRIPTION
**Pull request by whoozle**
Tested both version with my netis usb 802.11ac wifi dongle

### CODE REVIEW

**Comment by terencode** [comment]
Also reported as working by wolfland, fixing issue #30

**Comment by Boren** [comment]
Endorsing this. Works like a charm on ASUS-AC1300.

**Comment by coelner** [comment]
works fine under: 4.8.2-1-ARCH #1 SMP PREEMPT

**Comment by jcjordyn130** [comment]
This compile under 4.8.2-1-ARCH

**Comment by Grawp** [comment]
I'll merge this today. Sry I haven't had time lately.

**Comment by libcg** [comment]
Works well with 4.8.2 on an Archer T4U :+1:

**Pull request merged**
